### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by spyhunter99** [atsushieno/monodroid-schema-gen#1]
First of all, cool tool. I'm not sure if it solves the problem that i'm working on but it's at least a step in the right direction. (trying to get a close enough xsd for autocomplete in netbeans and other java IDEs (other than android studio).  

Just cloned and ran make (on osx) and got the following output
make
dmcs -debug monodroid-schema-gen.cs
dmcs -debug type-hierarchy-importer.cs extlibs/SgmlReader/sgmlreaderdll/_.cs
type-hierarchy-importer.cs(55,7): warning CS0219: The variable `wc' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlParser.cs(1500,17): warning CS0219: The variable`start' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlParser.cs(1535,17): warning CS0219: The variable `start' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlParser.cs(1564,18): warning CS0219: The variable`ch' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(829,19): warning CS0219: The variable `start' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(866,30): warning CS0219: The variable`n' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(1015,13): warning CS0162: Unreachable code detected
type-hierarchy-importer.cs(17,15): warning CS0414: The private field `Driver.atts' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(271,16): warning CS0414: The private field`Sgml.SgmlReader.rootElementName' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(285,16): warning CS0649: Field `Sgml.SgmlReader.startTag' is never assigned to, and will always have its default value`null'
Compilation succeeded - 10 warning(s)
mono --debug type-hierarchy-importer.exe
Processing http://developer.android.com/reference/android/view/View.html...
Processing http://developer.android.com/reference/android/widget/AnalogClock.html...
Processing http://developer.android.com/reference/android/widget/ImageView.html...
Processing http://developer.android.com/reference/android/inputmethodservice/KeyboardView.html...
Processing http://developer.android.com/reference/android/support/v7/app/MediaRouteButton.html...
Processing http://developer.android.com/reference/android/widget/ProgressBar.html...
Processing http://developer.android.com/reference/android/support/v4/widget/Space.html...
Processing http://developer.android.com/reference/android/view/SurfaceView.html...
Processing http://developer.android.com/reference/android/widget/TextView.html...
Processing http://developer.android.com/reference/android/view/TextureView.html...
Processing http://developer.android.com/reference/android/view/ViewGroup.html...
Processing http://developer.android.com/reference/android/view/ViewStub.html...
Processing http://developer.android.com/reference/android/widget/AbsListView.html...
Processing http://developer.android.com/reference/android/widget/AbsSeekBar.html...
Processing http://developer.android.com/reference/android/widget/AbsSpinner.html...
Processing http://developer.android.com/reference/android/widget/AbsoluteLayout.html...
Processing http://developer.android.com/reference/android/support/v7/widget/ActionMenuView.html...
Processing http://developer.android.com/reference/android/widget/AdapterView.html...
Processing http://developer.android.com/reference/android/widget/AdapterViewAnimator.html...
Processing http://developer.android.com/reference/android/widget/AdapterViewFlipper.html...
Processing http://developer.android.com/reference/android/support/design/widget/AppBarLayout.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatAutoCompleteTextView.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatButton.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatCheckBox.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatCheckedTextView.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatEditText.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatMultiAutoCompleteTextView.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatRadioButton.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatRatingBar.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatSpinner.html...
Processing http://developer.android.com/reference/android/support/v7/widget/AppCompatTextView.html...
Processing http://developer.android.com/reference/android/appwidget/AppWidgetHostView.html...
Processing http://developer.android.com/reference/android/widget/AutoCompleteTextView.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/BaseCardView.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/BrowseFrameLayout.html...
Processing http://developer.android.com/reference/android/widget/Button.html...
Processing http://developer.android.com/reference/android/widget/CalendarView.html...
Processing http://developer.android.com/reference/android/support/v7/widget/CardView.html...
Processing http://developer.android.com/reference/android/widget/CheckBox.html...
Processing http://developer.android.com/reference/android/widget/CheckedTextView.html...
Processing http://developer.android.com/reference/android/widget/Chronometer.html...
Processing http://developer.android.com/reference/android/support/design/widget/CollapsingToolbarLayout.html...
Processing http://developer.android.com/reference/android/widget/CompoundButton.html...
Processing http://developer.android.com/reference/android/support/v4/widget/ContentLoadingProgressBar.html...
Processing http://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.html...
Processing http://developer.android.com/reference/android/widget/DatePicker.html...
Processing http://developer.android.com/reference/android/widget/DialerFilter.html...
Processing http://developer.android.com/reference/android/widget/DigitalClock.html...
Processing http://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html...
Processing http://developer.android.com/reference/android/widget/EditText.html...
Processing http://developer.android.com/reference/android/widget/ExpandableListView.html...
Processing http://developer.android.com/reference/android/inputmethodservice/ExtractEditText.html...
Processing http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html...
Processing http://developer.android.com/reference/android/app/FragmentBreadCrumbs.html...
Processing http://developer.android.com/reference/android/support/v13/app/FragmentTabHost.html...
Processing http://developer.android.com/reference/android/widget/FrameLayout.html...
Processing http://developer.android.com/reference/android/opengl/GLSurfaceView.html...
Processing http://developer.android.com/reference/android/widget/Gallery.html...
Processing http://developer.android.com/reference/android/gesture/GestureOverlayView.html...
Processing http://developer.android.com/reference/android/support/v7/widget/GridLayout.html...
Processing http://developer.android.com/reference/android/widget/GridView.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/HorizontalGridView.html...
Processing http://developer.android.com/reference/android/widget/HorizontalScrollView.html...
Processing http://developer.android.com/reference/android/widget/ImageButton.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/ImageCardView.html...
Processing http://developer.android.com/reference/android/widget/ImageSwitcher.html...
Processing http://developer.android.com/reference/android/widget/LinearLayout.html...
Processing http://developer.android.com/reference/android/support/v7/widget/LinearLayoutCompat.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/ListRowHoverCardView.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/ListRowView.html...
Processing http://developer.android.com/reference/android/widget/ListView.html...
Processing http://developer.android.com/reference/android/widget/MediaController.html...
Processing http://developer.android.com/reference/android/widget/MultiAutoCompleteTextView.html...
Processing http://developer.android.com/reference/android/support/design/widget/NavigationView.html...
Processing http://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html...
Processing http://developer.android.com/reference/android/widget/NumberPicker.html...
Processing http://developer.android.com/reference/android/support/v4/view/PagerTabStrip.html...
Processing http://developer.android.com/reference/android/support/v4/view/PagerTitleStrip.html...
Processing http://developer.android.com/reference/android/widget/QuickContactBadge.html...
Processing http://developer.android.com/reference/android/widget/RadioButton.html...
Processing http://developer.android.com/reference/android/widget/RadioGroup.html...
Processing http://developer.android.com/reference/android/widget/RatingBar.html...
Processing http://developer.android.com/reference/android/support/v7/widget/RecyclerView.html...
Processing http://developer.android.com/reference/android/widget/RelativeLayout.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/RowHeaderView.html...
Processing http://developer.android.com/reference/android/widget/ScrollView.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/SearchBar.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/SearchEditText.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/SearchOrbView.html...
Processing http://developer.android.com/reference/android/support/v7/widget/SearchView.html...
Processing http://developer.android.com/reference/android/widget/SeekBar.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/ShadowOverlayContainer.html...
Processing http://developer.android.com/reference/android/widget/SlidingDrawer.html...
Processing http://developer.android.com/reference/android/support/v4/widget/SlidingPaneLayout.html...
Processing http://developer.android.com/reference/android/support/v7/widget/Space.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/SpeechOrbView.html...
Processing http://developer.android.com/reference/android/widget/Spinner.html...
Processing http://developer.android.com/reference/android/widget/StackView.html...
Processing http://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html...
Processing http://developer.android.com/reference/android/widget/Switch.html...
Processing http://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html...
Processing http://developer.android.com/reference/android/widget/TabHost.html...
Processing http://developer.android.com/reference/android/support/design/widget/TabLayout.html...
Processing http://developer.android.com/reference/android/widget/TabWidget.html...
Processing http://developer.android.com/reference/android/widget/TableLayout.html...
Processing http://developer.android.com/reference/android/widget/TableRow.html...
Processing http://developer.android.com/reference/android/widget/TextClock.html...
Processing http://developer.android.com/reference/android/support/design/widget/TextInputLayout.html...
Processing http://developer.android.com/reference/android/widget/TextSwitcher.html...
Processing http://developer.android.com/reference/android/widget/TimePicker.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/TitleView.html...
Processing http://developer.android.com/reference/android/widget/ToggleButton.html...
Processing http://developer.android.com/reference/android/support/v7/widget/Toolbar.html...
Processing http://developer.android.com/reference/android/media/tv/TvView.html...
Processing http://developer.android.com/reference/android/widget/TwoLineListItem.html...
Processing http://developer.android.com/reference/android/support/v17/leanback/widget/VerticalGridView.html...
Processing http://developer.android.com/reference/android/widget/VideoView.html...
Processing http://developer.android.com/reference/android/widget/ViewAnimator.html...
Processing http://developer.android.com/reference/android/widget/ViewFlipper.html...
Processing http://developer.android.com/reference/android/support/v4/view/ViewPager.html...
Processing http://developer.android.com/reference/android/widget/ViewSwitcher.html...
Processing http://developer.android.com/reference/android/webkit/WebView.html...
Processing http://developer.android.com/reference/android/widget/ZoomButton.html...
Processing http://developer.android.com/reference/android/widget/ZoomControls.html...
dmcs -debug get-android-r-styleable.cs extlibs/SgmlReader/sgmlreaderdll/_.cs
extlibs/SgmlReader/sgmlreaderdll/SgmlParser.cs(1500,17): warning CS0219: The variable `start' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlParser.cs(1535,17): warning CS0219: The variable`start' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlParser.cs(1564,18): warning CS0219: The variable `ch' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(829,19): warning CS0219: The variable`start' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(866,30): warning CS0219: The variable `n' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(1015,13): warning CS0162: Unreachable code detected
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(271,16): warning CS0414: The private field`Sgml.SgmlReader.rootElementName' is assigned but its value is never used
extlibs/SgmlReader/sgmlreaderdll/SgmlReader.cs(285,16): warning CS0649: Field `Sgml.SgmlReader.startTag' is never assigned to, and will always have its default value`null'
Compilation succeeded - 8 warning(s)
dmcs -debug convert-csv.cs
mono --debug convert-csv.exe > layout_schema_enumerations.xml
mono --debug get-android-r-styleable.exe
mono --debug ./monodroid-schema-gen.exe ""
Merging AbsoluteLayout_Layout into View
Merging ActionBar_LayoutParams into View

Unhandled Exception:
System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException (ExceptionResource resource) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/external/referencesource/mscorlib/system/throwhelper.cs:74 
  at System.Collections.Generic.Dictionary`2[System.String,System.String].Insert (System.String key, System.String value, Boolean add) [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[System.String,System.String].Add (System.String key, System.String value) [0x00000] in <filename unknown>:0 
  at Commons.AndroidSchemaGen.Driver.LoadXml () [0x001cf] in /Users/alex/projects/monodroid-schema-gen/monodroid-schema-gen.cs:193 
  at Commons.AndroidSchemaGen.Driver.Run (System.String[] args) [0x00002] in /Users/alex/projects/monodroid-schema-gen/monodroid-schema-gen.cs:31 
  at Commons.AndroidSchemaGen.Driver.Main (System.String[] args) [0x00007] in /Users/alex/projects/monodroid-schema-gen/monodroid-schema-gen.cs:17 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException (ExceptionResource resource) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/external/referencesource/mscorlib/system/throwhelper.cs:74 
  at System.Collections.Generic.Dictionary`2[System.String,System.String].Insert (System.String key, System.String value, Boolean add) [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[System.String,System.String].Add (System.String key, System.String value) [0x00000] in <filename unknown>:0 
  at Commons.AndroidSchemaGen.Driver.LoadXml () [0x001cf] in /Users/alex/projects/monodroid-schema-gen/monodroid-schema-gen.cs:193 
  at Commons.AndroidSchemaGen.Driver.Run (System.String[] args) [0x00002] in /Users/alex/projects/monodroid-schema-gen/monodroid-schema-gen.cs:31 
  at Commons.AndroidSchemaGen.Driver.Main (System.String[] args) [0x00007] in /Users/alex/projects/monodroid-schema-gen/monodroid-schema-gen.cs:17 
make: **\* [android-layout-xml.xsd] Error 1

**Comment by atsushieno** [comment]
Hello. It was written when I was at Novell and not in their Android team, to help their work to some extent. They kind of took over the sources to generate the schemas that they use, that matches my intention and I don't work on this tool anymore. If you need some bugfixes in Xamairn.Android, you file bugs at bugzilla.xamarin.com, or ask support@xamarin.com for help if you are customer.
